version: '3'

services:
  db:
    volumes: 
      - transferpay-db-data:/var/lib/mysql
    build:
      context: .
      dockerfile: ./docker/mariadb/Dockerfile
    image: "${MARIADB_CONTAINER_NAME}"
    container_name: "${MARIADB_CONTAINER_NAME}"
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWD}"
    ports:
      - "${DB_PORT}:3306"
    networks:
      - transferpay-network

  api:
    volumes: 
      - ./api:/var/www/html
    image: "${API_CONTAINER_NAME}"
    container_name: "${API_CONTAINER_NAME}"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        APIHTTPPORT: "${API_HTTP_PORT}"
        APIHTTPSPORT: "${API_HTTPS_PORT}"
        APIKEY: "${API_KEY}"
        APINAME: "${API_NAME}"
        APIURL: "${API_URL}"
        APPENV: "local"
        DBNAME: "${DB_NAME}"
        DBPASS: "${DB_PASSWD}"
        DBPORT: "${DB_PORT}"
        DBUSER: "${DB_USER}"
        TIMEZONE: "${TIMEZONE}"
    depends_on:
      - "db"
    networks:
      - transferpay-network

  webserver:
    volumes: 
      - ./api:/var/www/html
    image: "${NGINX_CONTAINER_NAME}"
    container_name: "${NGINX_CONTAINER_NAME}"
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "${API_HTTP_PORT}:80"
      - "${API_HTTPS_PORT}:443"
    depends_on:
      - "api"
    networks:
      - transferpay-network

networks:
  transferpay-network:
    driver: bridge

volumes:
  transferpay-db-data: